# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:        
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - run: yarn
        
      - run: npm rebuild node-sass

      - run: yarn generate
      
      - uses: ad-m/github-push-action@v0.6.0
        with:
          # Token for the repo. Can be passed in using $\{{ secrets.GITHUB_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Repository name to push. Default or empty value represents current github repository (${GITHUB_REPOSITORY})
          repository: ${GITHUB_REPOSITORY} # optional, default is 
          # Destination branch to push changes
          branch: gh-pages # optional, default is master
          # Directory to change to before pushing.
          directory: dist # optional, default is .
